site_name: Optimus Documentation
site_url: https://rayoh.github.io/optimus-documentation/
nav:
  - Home: index.md
  - Getting Started:
     - 'Installation': getting-started/install.md
     - 'Quick Start Guide': getting-started/quickstart.md
     - 'Configuration': getting-started/configuration.md 
  - User Interface:
     - 'Navigation': user-interface/navigation.md
     - 'Excel Front End': user-interface/launcher.md
  - Creating Automation Flows:
     - 'Basic Concepts': basics/language.md
     - 'Using Templates': basics/templates.md
     - 'Libraries': basics/libraries.md
  - Advanced Features:
     - 'Orchestration': advance/orchestration.md
     - 'Python and Jupyter Notebooks': advance/jupyternotebook.md
     - 'Pandas Integration': advance/pandas.md
     - 'Scaling': advance/scaling.md     
     - 'AI agents': advance/ai.md  
     - 'Power BI Integration': advance/powerbi.md  
     - 'Outlook Email Integration': advance/email.md  
  - Others:
     - 'Security': others/security.md
     - 'Data Management': others/onedrive.md
     - 'Troubleshooting and FAQs': others/bugs.md
     - 'Packaging Installation': developers/install_packaging.md
     - 'Common Issues': todo.md
     - 'Use Cases and Projects': others/usecases.md
     - 'Community Forums and Support': todo.md
     - 'Glossary': todo.md
     - 'References': SCRAPBOOK.md
     - 'MK Docs Guide': others/mkdocs_guide.md     

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/james-willett
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: |
  &copy; 2023 <a href="https://github.com/rayoh"  target="_blank" rel="noopener">Raymond Oh</a>
